name: "01 - Simple exemple"

on push:

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: |
          echo "Push détecté !"
          echo "Auteur : ${{ github.actor }}"
          echo "Auteur : ${{ github.ref_name }}"
          echo "Auteur : ${{ github.sha }}"